# Generated by Django 3.0.5 on 2021-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0002_auto_20210221_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=999, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
