# Generated by Django 3.0.5 on 2021-02-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0005_auto_20210221_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='name',
        ),
    ]
