# Generated by Django 3.0.5 on 2021-02-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0007_auto_20210221_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='アイコン'),
        ),
    ]
