# Generated by Django 3.0.5 on 2021-02-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0009_auto_20210221_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='所属')),
            ],
            options={
                'verbose_name': '所属',
                'verbose_name_plural': '所属',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='氏名'),
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Specific Departments for this user.', related_name='user_set', related_query_name='user', to='cosmicsns.Department', verbose_name='所属'),
        ),
    ]
