# Generated by Django 3.0.5 on 2021-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0012_auto_20210221_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unchiburi',
            field=models.BooleanField(default=False),
        ),
    ]
