# Generated by Django 3.0.5 on 2021-02-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0013_user_unchiburi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unchiburi',
        ),
    ]
