# Generated by Django 3.0.5 on 2021-02-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0014_remove_user_unchiburi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
