# Generated by Django 3.0.5 on 2021-02-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0015_auto_20210222_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='introduce',
        ),
    ]
