# Generated by Django 3.0.5 on 2021-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0016_remove_user_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
