# Generated by Django 3.0.5 on 2021-02-24 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmicsns', '0017_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='profiles', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif', 'jpeg'])]),
        ),
    ]
